services:
  db:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_DB_PORT}:${POSTGRES_PORT}"
    volumes:
      - vol-pgdata:/var/lib/postgresql/data
    networks:
      - taxi_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${HOST_PGADMIN_PORT}:80"
    volumes:
      - vol-pgadmin_data:/var/lib/pgadmin
    networks:
      - taxi_network

volumes:
  vol-pgdata:
  vol-pgadmin_data:

networks:
  taxi_network: